#!/bin/sh
set -eu

APP_DB_USER="${APP_DB_USER:-app_user}"
APP_DB_PASS="${APP_DB_PASS:-change-me}"
POSTGRES_DB="${POSTGRES_DB:-whatsapp_saas}"

sql_escape() {
  printf "%s" "$1" | sed "s/'/''/g"
}

APP_DB_USER_ESCAPED="$(sql_escape "$APP_DB_USER")"
APP_DB_PASS_ESCAPED="$(sql_escape "$APP_DB_PASS")"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_roles WHERE rolname = '${APP_DB_USER_ESCAPED}'
  ) THEN
    EXECUTE 'CREATE USER "${APP_DB_USER_ESCAPED}" WITH PASSWORD ''${APP_DB_PASS_ESCAPED}''';
  ELSE
    EXECUTE 'ALTER USER "${APP_DB_USER_ESCAPED}" WITH PASSWORD ''${APP_DB_PASS_ESCAPED}''';
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${APP_DB_USER_ESCAPED}";
GRANT USAGE ON SCHEMA public TO "${APP_DB_USER_ESCAPED}";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "${APP_DB_USER_ESCAPED}";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "${APP_DB_USER_ESCAPED}";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${APP_DB_USER_ESCAPED}";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "${APP_DB_USER_ESCAPED}";
EOSQL
